PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD /GJAAUTO/CKTB003-AUTO .
    FIELD /GJAAUTO/CKTB003-OPERA .
    FIELD /GJAAUTO/CKTB003-ETAPA .
    FIELD /GJAAUTO/CKTB003-DESCR .
    FIELD /GJAAUTO/CKTB003-TPETA .
    FIELD /GJAAUTO/CKTB003-ROTIN .
    FIELD /GJAAUTO/CKTB003-MAPEA .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD /GJAAUTO/CKTB003-AUTO .
    FIELD /GJAAUTO/CKTB003-OPERA .
    FIELD /GJAAUTO/CKTB003-ETAPA .
  module detail_pai.
 endchain.
