PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/GJAAUTO/CKTB003 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /GJAAUTO/CKTB003-AUTO .
    FIELD /GJAAUTO/CKTB003-OPERA .
    FIELD /GJAAUTO/CKTB003-ETAPA .
    FIELD /GJAAUTO/CKTB003-DESCR .
    FIELD /GJAAUTO/CKTB003-TPETA .
    FIELD /GJAAUTO/CKTB003-ROTIN .
    FIELD /GJAAUTO/CKTB003-MAPEA .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /GJAAUTO/CKTB003-AUTO .
    FIELD /GJAAUTO/CKTB003-OPERA .
    FIELD /GJAAUTO/CKTB003-ETAPA .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
