PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD /GJAAUTO/CKTB002-AUTO .
    FIELD /GJAAUTO/CKTB002-OPERA .
    FIELD /GJAAUTO/CKTB002-DESCR .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD /GJAAUTO/CKTB002-AUTO .
    FIELD /GJAAUTO/CKTB002-OPERA .
  module detail_pai.
 endchain.
