PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD /GJAAUTO/CKTB001-AUTO .
    FIELD /GJAAUTO/CKTB001-DESCR .
    FIELD /GJAAUTO/CKTB001-ICON .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD /GJAAUTO/CKTB001-AUTO .
  module detail_pai.
 endchain.
